Repository owncloud/user_management, pull requests merged in 2018-11, with the labels that each got.

#95 strict="true"
  tests/unit/phpunit.xml
Labels: 3 - To Review

#101 Skip invalid quota test - issue 100
  tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#102 Remove explicit use of user password while user logs in
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#99 Add new make file targets
  .drone.yml
  Makefile
  composer.json
  composer.lock
  vendor-bin/owncloud-codestyle/composer.json
  vendor-bin/owncloud-codestyle/composer.lock
Labels: 3 - To Review, QA-team

#105 Adjust acceptance test steps changed in core
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#106 drop lock file for vendor-bin dependencies
  .gitignore
  vendor-bin/owncloud-codestyle/composer.lock
Labels: 4 - To release, QA-team

#108 webUI Acceptance tests to verify setting password with to valid and invalid values
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#110 Fix steps changed in core
  tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
  tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#104 Display error message in new password form
  js/setpassword.js
  lib/Controller/UsersController.php
  tests/js/karma.config.js
  tests/js/setpasswordSpec.js
  tests/unit/UsersControllerTest.php
Labels: 3 - To Review

#94 Replace notification with confirm dialog for user deletion
  js/deleteHandler.js
  js/groups.js
  js/users.js
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UserPageElement/GroupList.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature
  tests/js/deleteHandlerSpec.js
Labels: 3 - To Review

#111 Delete dead code from the deleteHandler
  js/deleteHandler.js
Labels: 4 - To release

#114 Move phpunit.xml to root, use phpunit from core, remove lint
  .drone.yml
  .gitignore
  Makefile
  composer.json
  composer.lock
  phpunit.xml
Labels: 3 - To Review, QA-team

#119 adjust acceptance test time constant names
  tests/acceptance/features/lib/DisabledUserPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests
