Repository owncloud/user_management, pull requests merged in 2018-08, with the labels that each got.

#46 Implement ocPath through testing app
  tests/acceptance/config/behat.yml
Labels: 3 - To Review

#47 Remove unneeded SKELETON_DIR in .drone.yml
  .drone.yml
Labels: 2 - Developing

#49 Acceptance test code standard
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
Labels: 3 - To Review, dev:acceptance-tests

#56 Do not use GIT_REFERENCE
  .drone.yml
Labels: 3 - To Review

#53 Be consistent in acceptance test steps 'when the administrator'
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#48 Make email field as default to create user
  appinfo/routes.php
  css/setpassword.css
  js/setpassword.js
  js/users.js
  lib/Controller/PageController.php
  lib/Controller/UsersController.php
  lib/Exception/InvalidUserTokenException.php
  lib/Exception/UserTokenException.php
  lib/Exception/UserTokenExpiredException.php
  lib/Exception/UserTokenMismatchException.php
  templates/main.php
  templates/new_user/email-html.php
  templates/new_user/resendtokenbymail.php
  templates/new_user/setpassword.php
  templates/new_user/tokensendnotify.php
  templates/part.createuser.php
  tests/acceptance/features/lib/UsersPage.php
  tests/unit/ChangePasswordControllerTest.php
  tests/unit/UsersControllerTest.php
Labels: 3 - To Review
