Repository owncloud/user_management, pull requests merged in 2019-07, with the labels that each got.

#187 Test for creating users
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/webUIAddUsers/addUsers.feature
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#192 user management app test against latest tarball
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#195 Added description for the user settings section
  templates/main.php
Labels: 3 - To Review, enhancement

#193 fix phpstan 'Undefined variable: ' reported for togglegroups.php
  ajax/togglegroups.php
Labels: 3 - To Review
